# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cippaxonk

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'cippaxonk-flex'
  STORAGE_ACCOUNT: 'cippstgaxonk'
  BLOB_CONTAINER: 'app-package-cippaxonkflex-9684844'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create deployment package
        run: zip -r release.zip . --exclude "*.git*" --exclude ".github/*"

      - name: Upload package to blob storage
        run: |
          az storage blob upload \
            --account-name ${{ env.STORAGE_ACCOUNT }} \
            --container-name ${{ env.BLOB_CONTAINER }} \
            --name release.zip \
            --file release.zip \
            --overwrite \
            --auth-mode login

      - name: Sync function app
        run: |
          az functionapp restart \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group Cipp-West-Europe